# Generated by Django 5.2.7 on 2025-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeStart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
